### PR TITLE
Add link to mastodon profile

### PR DESCRIPTION
**Pull request by sethaxen**
----
:books: Documentation preview :books:: https://arviz-project--27.org.readthedocs.build/en/27/

### CODE REVIEW

**Comment by sethaxen** [comment]
@OriolAbril, any idea why the docs preview build doesn't include the Mastodon link?

**Comment by OriolAbril** [comment]
The syntax is wrong. It now uses html syntax for links but it should be the text we want to be displayed first and the url between angle brackets later like the other items

**Comment by sethaxen** [comment]
> The syntax is wrong. It now uses html syntax for links but it should be the text we want to be displayed first and the url between angle brackets later like the other items

Somehow we need to make sure the `rel="me"` is included in the rendered `<a>` tag, since this will let Mastodon verify the URL (effectively how verification works on Mastodon). Do you know how we can do that?

**Comment by OriolAbril** [comment]
We'll need to change how we add those links to the sidebar. I will take a look, I think it will be something sown in https://pradyunsg.me/furo/customisation/sidebar/, probably writing the links as small html file and adding it in html sidebars variable

**Review by OriolAbril — APPROVED** [review]
@sethaxen I changed the way in which external links are added to be able to use raw html and the `rel="me"` part. Please double check everything looks ok and that the content is indeed correct and merge the PR yourself

**Comment by sethaxen** [comment]
LGTM, thanks!

**Pull request merged**
